include $(GOROOT)/src/Make.inc

TARG=mlgo/cluster
GOFILES=\
				cluster.go\
				metrics.go\
				kmeans.go\
				kmedians.go\
				kmedoids.go\
				mixmodel.go\
				heap.go\
				activeset.go\
				hclust.go\

include $(GOROOT)/src/Make.pkg
