include $(GOROOT)/src/Make.inc

TARG=mlgo/cluster
GOFILES=\
				cluster.go\
				partitions.go\
				metrics.go\
				kmeans.go\
				kmedians.go\
				kmedoids.go\
				mixmodel.go\
				heap.go\
				activeset.go\
				unionfind.go\
				coordinates.go\
				hclust.go\
				hclust_generic.go\
				hclust_single.go\

include $(GOROOT)/src/Make.pkg
